export const ROUTES = {
  public: {
    home: '/real-estate',
    listing: '/real-estate/listing',
    properties: '/real-estate/properties',
    propertyDetail: '/real-estate/property/:slug',
    compare: '/real-estate/compare',
    login: '/real-estate/auth/login',
    signup: '/real-estate/auth/signup',
  },
  protected: {
    dashboard: '/real-estate/dashboard',
    postProperty: '/real-estate/post-property',
    editProperty: '/real-estate/edit-property/:slug',
    saved: '/real-estate/saved',
    workspace: '/real-estate/workspace',
    workspaceProperties: '/real-estate/workspace/properties',
    workspaceCompare: '/real-estate/workspace/compare',
    workspaceLeads: '/real-estate/workspace/leads',
    workspaceSettings: '/real-estate/workspace/settings',
    listingsAll: '/real-estate/workspace/listings/all',
    listingsPlain: '/real-estate/workspace/listings/plain',
    listingsBasic: '/real-estate/workspace/listings/basic',
    listingsPlatinum: '/real-estate/workspace/listings/platinum',
    listingsPremium: '/real-estate/workspace/listings/premium',
    admin: '/real-estate/admin',
  },
  legacy: {
    login: '/real-estate/login',
    register: '/real-estate/register',
    post: '/real-estate/post',
    dashboard: '/real-estate/dashboard',
    properties: '/real-estate/properties',
    propertyDetail: '/real-estate/properties/:slug',
    createProperty: '/real-estate/create-property',
    manage: '/real-estate/manage',
    leads: '/real-estate/leads',
  },
};

export const SIDEBAR_ITEMS = [
  { label: 'Overview', path: ROUTES.protected.dashboard, icon: 'layout-dashboard', permission: 'dashboard:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'All Listings', path: ROUTES.protected.listingsAll, icon: 'building-2', permission: 'property:list', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Basic Listings', path: ROUTES.protected.listingsPlain, icon: 'building-2', permission: 'property:list', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Silver Listings', path: ROUTES.protected.listingsBasic, icon: 'building-2', permission: 'property:list', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Gold Listings', path: ROUTES.protected.listingsPlatinum, icon: 'building-2', permission: 'property:list', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Platinum Listings', path: ROUTES.protected.listingsPremium, icon: 'building-2', permission: 'property:list', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Create Property', path: ROUTES.protected.postProperty, icon: 'plus-circle', permission: 'property:create', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Saved', path: ROUTES.protected.saved, icon: 'heart', permission: 'saved:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Compare', path: ROUTES.protected.workspaceCompare, icon: 'columns-3', permission: 'compare:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Leads', path: ROUTES.protected.workspaceLeads, icon: 'inbox', permission: 'lead:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Analytics', path: ROUTES.protected.dashboard, icon: 'chart-column', permission: 'analytics:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Messages', path: ROUTES.protected.workspace, icon: 'messages-square', permission: 'message:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  // { label: 'Workspace', path: ROUTES.protected.workspace, icon: 'layers-3', permission: 'workspace:view', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
  { label: 'Admin Review', path: ROUTES.protected.admin, icon: 'shield-check', permission: 'property:moderate', roles: ['ADMIN'] },
  { label: 'Settings', path: ROUTES.protected.workspaceSettings, icon: 'settings-2', permission: 'account:manage', roles: ['ADMIN', 'SELLER', 'BUILDER', 'AGENT', 'OWNER'] },
];

export const DASHBOARD_SUMMARY = [
  { label: 'Properties', key: 'propertyCount' },
  { label: 'Leads', key: 'leadCount' },
  { label: 'Saved', key: 'savedCount' },
  { label: 'Pending', key: 'pendingCount' },
];
